# Nom du workflow
name: First WorkFlow

# Déclancheur du workflow
on:
  - workflow_dispatch  # Manuellement
  - push  # Au push

# Actions réalisées au déclanchement du workflow
jobs:
  # Définition de l'action 1
  job-1:
    name: Job 1
    # Définition du système d'exploitation
    runs-on: ubuntu-latest
    # Définition des étapes de notre action
    steps:
      # On donne un nom à notre étape puis notre commande
      - name: Say Hello
        run: echo "Hello World!"
      - name: Say Goodbye
        run: echo "Goodbye!"

  job-2:
    # Dépendance au job-1 (Si job-1 réussi alors le job-2 s'éxécute)
    needs: job-1
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World!"