name: artifact

on: push

jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v6
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: build application
        run: npm run build
      - name: upload du build
        uses: actions/upload-artifact@v7
        with:
          name: mon_app
          path: dist